// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function greet(name) {
  return "Hello " + name;
}

console.log("Hello boris");

function add(x, y, z) {
  return (x + y | 0) + z | 0;
}

console.log(14);

exports.greet = greet;
exports.add = add;
/*  Not a pure module */
