// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var test = "Reason1";

console.log(test);

console.log("yo");

var word = "Master";

var match = word === "Master";

console.log(match ? "Happy" : "Sad");

var match$1 = word === "!Master";

console.log(match$1 ? "Happy" : "Sad");

exports.test = test;
exports.word = word;
/*  Not a pure module */
