// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var newScore = 20;

console.log(newScore);

console.log("Enjoying the docs so far?");

var message = "helloo world";

console.log(message);

var greeting = "hello!";

var score = 10;

var displayGreeting = true;

exports.greeting = greeting;
exports.score = score;
exports.newScore = newScore;
exports.displayGreeting = displayGreeting;
exports.message = message;
/*  Not a pure module */
