// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


console.log(5);

console.log(1);

console.log(21.7 * 2);

var greeting = "Hello master";

console.log(greeting);

var myInt = 5;

exports.myInt = myInt;
exports.greeting = greeting;
/*  Not a pure module */
