// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Greet$ReasonmlDemoModules = require("./Greet.bs.js");

Pervasives.print_string("My name is: ");

Pervasives.print_string(Greet$ReasonmlDemoModules.greet("Marcell ", "Ciszek Druzynski"));

Pervasives.print_newline(/* () */0);

/*  Not a pure module */
