// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

Pervasives.print_string("Hello world!");

Pervasives.print_newline(/* () */0);

/*  Not a pure module */
