// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var check = 5.3 + 3.3;

var array = /* array */[
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10
];

for(var i = 0 ,i_finish = array.length - 1 | 0; i <= i_finish; ++i){
  Pervasives.print_int(i);
  Pervasives.print_string(" \n");
}

var a = 2;

var b = 4;

exports.a = a;
exports.b = b;
exports.check = check;
exports.array = array;
/*  Not a pure module */
