// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var a = "Helloworld";

Pervasives.print_string("hello");

var res = "one";

var res2 = true;

var r_001 = /* tuple */[
  2,
  3
];

var r = /* tuple */[
  2,
  r_001
];

var day = "Monday";

var resOfZzz = 27;

var myIfElese = Pervasives.print_string("\nHello\n");

String(3);

var check = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var check2 = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

Caml_obj.caml_equal(check, check2);

var b = /* tuple */[
  45,
  45.4,
  /* tuple */[
    "apple",
    "banana",
    /* tuple */[
      43,
      true,
      false
    ]
  ]
];

var vector3 = /* tuple */[
  1,
  2,
  3
];

var value = 1;

var tuple = /* tuple */[
  true,
  true
];

var t = /* tuple */[
  45,
  /* tuple */[
    2,
    3
  ]
];

var zzz = /* tuple */[
  3,
  9
];

var num = 3;

var z = check;

exports.a = a;
exports.b = b;
exports.vector3 = vector3;
exports.value = value;
exports.res = res;
exports.tuple = tuple;
exports.res2 = res2;
exports.t = t;
exports.r = r;
exports.day = day;
exports.zzz = zzz;
exports.resOfZzz = resOfZzz;
exports.myIfElese = myIfElese;
exports.num = num;
exports.check = check;
exports.check2 = check2;
exports.z = z;
/*  Not a pure module */
