// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function f(x, y) {
  return Caml_int32.imul(Caml_int32.imul(x, x), y);
}

function isEven(x) {
  return x % 2 === 0;
}

var a = "a";

var c = "c";

exports.f = f;
exports.isEven = isEven;
exports.a = a;
exports.c = c;
/*  Not a pure module */
