// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

var toLower = $$String.lowercase;

console.log($$String.lowercase("HellO My FrIEnD"));

exports.toLower = toLower;
/*  Not a pure module */
