// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var x = "Legia";

Pervasives.print_string(x);

Pervasives.print_string("\n");

Pervasives.print_string("Warszawa");

Pervasives.print_string("\n");

Pervasives.print_string(x);

Pervasives.print_string("\n");

Pervasives.print_string("Hello");

Pervasives.print_int(123);

Pervasives.print_string("mama");

var res = "correct , 5 + 5  = 10";

var res2 = "5 * 5  = 25";

var t = /* tuple */[
  56,
  43,
  true,
  "hi"
];

var d = "hi";

var a = 56;

var b = 43;

var c = true;

var sum = 10;

var myBool = true;

exports.x = x;
exports.t = t;
exports.d = d;
exports.a = a;
exports.b = b;
exports.c = c;
exports.sum = sum;
exports.res = res;
exports.res2 = res2;
exports.myBool = myBool;
/*  Not a pure module */
