// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function getAnimal(anim) {
  return "this is a " + anim;
}

function getTitle(cond, exp) {
  if (cond) {
    return exp;
  } else {
    return exp + " this is title ";
  }
}

console.log("test");

function getTitle2(cond, exp) {
  if (cond) {
    return exp;
  } else {
    return exp + "Reason ";
  }
}

console.log(" MLReason ");

var dog = "Doggie";

var duck = "ducky";

exports.dog = dog;
exports.duck = duck;
exports.getAnimal = getAnimal;
exports.getTitle = getTitle;
exports.getTitle2 = getTitle2;
/*  Not a pure module */
