// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function handleClick(_event) {
  console.log("clicked!");
  return /* () */0;
}

function Component1(Props) {
  var message = Props.message;
  var match = React.useReducer((function (oldState, actionInTheNewState) {
          return actionInTheNewState;
        }), undefined);
  var setUsers = match[1];
  var users = match[0];
  React.useEffect((function () {
          var data = (require('./data.json'));
          data.name;
          Curry._1(setUsers, Caml_option.some(data));
          return undefined;
        }), ([]));
  if (users !== undefined) {
    React.createElement("div", {
          onClick: handleClick
        }, Caml_option.valFromOption(users).name);
  } else {
    React.createElement("div", {
          onClick: handleClick
        }, message);
  }
  return React.createElement("div", undefined, message);
}

var make = Component1;

exports.handleClick = handleClick;
exports.make = make;
/* react Not a pure module */
