// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function canDring(age) {
  if (age < 18) {
    return Pervasives.print_string("You are to young ");
  } else if (age === 18) {
    return Pervasives.print_string("Welcome fresh men ");
  } else if (age >= 18) {
    return Pervasives.print_string("Welcome master ");
  } else {
    return 0;
  }
}

console.log(canDring(5));

console.log(canDring(18));

console.log(canDring(28));

exports.canDring = canDring;
/*  Not a pure module */
