// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var mult = Caml_int32.imul;

function times3(param) {
  return Caml_int32.imul(3, param);
}

var num = 9;

function addText(addition, text) {
  return text + addition;
}

var print = "Mistrzem polski jest Legia";

console.log(print);

exports.mult = mult;
exports.times3 = times3;
exports.num = num;
exports.addText = addText;
exports.print = print;
/*  Not a pure module */
