// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function speak(a) {
  if (a.tag) {
    return a[0] + " says: woof";
  } else {
    var name = a[0];
    if (name === "Carol") {
      return "omg it is carol!";
    } else {
      return name + " says: meow";
    }
  }
}

console.log(speak(/* Cat */Block.__(0, ["Corol"])));

console.log(speak(/* Dog */Block.__(1, ["Whieksy"])));

console.log(speak(/* Cat */Block.__(0, ["bobby"])));

function gcd(_a, _b) {
  while(true) {
    var b = _b;
    var a = _a;
    var r = Caml_int32.mod_(a, b);
    if (r !== 0) {
      _b = r;
      _a = b;
      continue ;
    } else {
      return b;
    }
  };
}

console.log(gcd(2, 32));

exports.speak = speak;
exports.gcd = gcd;
/*  Not a pure module */
