// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var message = Pervasives.print_string("Good morning");

var isMorning = true;

exports.isMorning = isMorning;
exports.message = message;
/* message Not a pure module */
