// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function hello(param) {
  return "Hello World";
}

console.log("Hello World");

exports.hello = hello;
/*  Not a pure module */
