// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

Pervasives.print_string("five \n");

var five = 5;

var num = 45;

var numWithoutAnTypeButStillIsAnType = 10;

exports.five = five;
exports.num = num;
exports.numWithoutAnTypeButStillIsAnType = numWithoutAnTypeButStillIsAnType;
/*  Not a pure module */
