// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var myList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var message = myList ? "The head of the list is the string " + String(1) : "this is an empty list";

var myArr = /* array */[
  "hello",
  "MArcell",
  "How are you?"
];

var firstIndex = Caml_array.caml_array_get(myArr, 0);

Random.self_init(/* () */0);

var foo = /* record */[/* contents */5];

var five = foo[0];

console.log(five);

foo[0] = 12;

console.log(foo);

var bar = /* record */[/* contents */4];

var seven = foo[/* contents */0];

foo[/* contents */0] = 8;

console.log(seven);

var foo2 = 15;

Pervasives.print_int(foo2);

var apple = /* record */[
  /* sort */"granny smith",
  /* colour */"green",
  /* rank */2,
  /* delicious */true
];

var xStart = 1;

var xEnd = 15;

var ten = 10;

exports.apple = apple;
exports.myList = myList;
exports.message = message;
exports.myArr = myArr;
exports.firstIndex = firstIndex;
exports.xStart = xStart;
exports.xEnd = xEnd;
exports.foo = foo;
exports.five = five;
exports.bar = bar;
exports.seven = seven;
exports.ten = ten;
exports.foo2 = foo2;
/* message Not a pure module */
