// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function func(x) {
  return x + 6 | 0;
}

function factorial(n) {
  if (n <= 1) {
    return 1;
  } else {
    return Caml_int32.imul(n, factorial(n - 1 | 0));
  }
}

function isEven(n) {
  if (n === 0) {
    return true;
  } else {
    Pervasives.print_int(n);
    Pervasives.print_string(" \n this is from the isEven function \n");
    return isOdd(n - 1 | 0);
  }
}

function isOdd(n) {
  if (n === 0) {
    return false;
  } else {
    Pervasives.print_int(n);
    Pervasives.print_string(" \n this is from the isOdd function \n");
    return isEven(n - 1 | 0);
  }
}

console.log(isEven(2));

exports.func = func;
exports.factorial = factorial;
exports.isEven = isEven;
exports.isOdd = isOdd;
/*  Not a pure module */
