// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var boris = /* record */[
  /* name */"Boris",
  /* age */23
];

console.log(boris);

exports.boris = boris;
/*  Not a pure module */
