// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var a = "Helloworld";

Pervasives.print_string("hello");

var res = "one";

var res2 = true;

var r_001 = /* tuple */[
  2,
  3
];

var r = /* tuple */[
  2,
  r_001
];

var day = "Monday";

var resOfZzz = 27;

var myIfElese = Pervasives.print_string("\nHello\n");

console.log(myIfElese);

var b = /* tuple */[
  45,
  45.4,
  /* tuple */[
    "apple",
    "banana",
    /* tuple */[
      43,
      true,
      false
    ]
  ]
];

var vector3 = /* tuple */[
  1,
  2,
  3
];

var value = 1;

var tuple = /* tuple */[
  true,
  true
];

var t = /* tuple */[
  45,
  /* tuple */[
    2,
    3
  ]
];

var zzz = /* tuple */[
  3,
  9
];

exports.a = a;
exports.b = b;
exports.vector3 = vector3;
exports.value = value;
exports.res = res;
exports.tuple = tuple;
exports.res2 = res2;
exports.t = t;
exports.r = r;
exports.day = day;
exports.zzz = zzz;
exports.resOfZzz = resOfZzz;
exports.myIfElese = myIfElese;
/*  Not a pure module */
