// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var starWarsChars = /* array */[
  "Solo",
  "Luke",
  "Anakin",
  "Lea"
];

var doggies = /* array */[
  "snickers",
  "bobby",
  "Korek"
];

var createArray = Caml_array.caml_make_vect;

Caml_array.caml_make_vect(5, "korek");

Caml_array.caml_make_vect(12, 3);

for(var i = 0 ,i_finish = doggies.length; i <= i_finish; ++i){
  console.log(Caml_array.caml_array_get(doggies, i));
}

var getByIndex = Caml_array.caml_array_get;

Caml_array.caml_array_get(doggies, 0);

exports.starWarsChars = starWarsChars;
exports.doggies = doggies;
exports.createArray = createArray;
exports.getByIndex = getByIndex;
/*  Not a pure module */
