// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var starWarsChars = /* array */[
  "Solo",
  "Luke",
  "Anakin",
  "Lea"
];

var doggies = /* array */[
  "snickers",
  "bobby",
  "Korek"
];

var createArray = Caml_array.caml_make_vect;

Caml_array.caml_make_vect(5, "korek");

Caml_array.caml_make_vect(12, 3);

for(var i = 0 ,i_finish = doggies.length; i <= i_finish; ++i){
  console.log(Caml_array.caml_array_get(doggies, i));
}

var getByIndex = Caml_array.caml_array_get;

Caml_array.caml_array_get(doggies, 0);

var fruits = /* array */[
  "granny smith",
  "yellow something",
  "polish cherries"
];

if (fruits.length !== 3) {
  throw [
        Caml_builtin_exceptions.match_failure,
        /* tuple */[
          "Arr.re",
          22,
          4
        ]
      ];
}

var apple = fruits[0];

var banana = fruits[1];

var cherry = fruits[2];

exports.starWarsChars = starWarsChars;
exports.doggies = doggies;
exports.createArray = createArray;
exports.getByIndex = getByIndex;
exports.fruits = fruits;
exports.apple = apple;
exports.banana = banana;
exports.cherry = cherry;
/*  Not a pure module */
