// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

Caml_obj.caml_equal(/* tuple */[
      7,
      2
    ], /* tuple */[
      7,
      2
    ]);

Caml_obj.caml_equal(/* tuple */[
      8,
      2
    ], /* tuple */[
      4,
      3
    ]);

Caml_obj.caml_notequal(/* tuple */[
      7,
      2
    ], /* tuple */[
      7,
      2
    ]);

Caml_obj.caml_notequal(/* tuple */[
      7,
      2
    ], /* tuple */[
      7,
      1
    ]);

var x = /* tuple */[
  45,
  21
];

var y = x;

exports.x = x;
exports.y = y;
/*  Not a pure module */
