// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var x = "Legia";

Pervasives.print_string(x);

Pervasives.print_string("\n");

Pervasives.print_string("Warszawa");

Pervasives.print_string("\n");

Pervasives.print_string(x);

Pervasives.print_string("\n");

Pervasives.print_string("Hello");

console.log(123);

Pervasives.print_int(123);

var b = 123;

exports.x = x;
exports.b = b;
/*  Not a pure module */
