// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function getFirstName(person) {
  return person[/* firstName */0];
}

var borisParents = /* record */[
  /* father */"Oleg",
  /* mother */"Helga"
];

var boris = /* record */[
  /* first */"boris",
  /* last */"Smirinoff",
  /* city */"Siberia",
  /* parents */borisParents
];

var luke = /* record */[
  /* firstName */"Luke",
  /* lastName */"Skywalker",
  /* personIs */"jedi",
  /* age */45354534
];

var a = "Luke";

var snickers = /* record */[
  /* age */2,
  /* name */"Snickers",
  /* breed */"pug"
];

var age = 2;

var name = "Snickers";

var breed = "pug";

var father = "Oleg";

exports.luke = luke;
exports.getFirstName = getFirstName;
exports.a = a;
exports.snickers = snickers;
exports.age = age;
exports.name = name;
exports.breed = breed;
exports.borisParents = borisParents;
exports.boris = boris;
exports.father = father;
/* No side effect */
