// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var karol = /* record */[
  /* name */"bobby",
  /* age */4,
  /* cool */false
];

var pysia = /* record */[
  /* name */"bobby",
  /* age */14,
  /* cool */true
];

var rocketToPluto = /* record */[
  /* rocket */"spacX34",
  /* destination */"Moon",
  /* fuelType */"poer force x-4344"
];

console.log(rocketToPluto);

rocketToPluto[/* destination */1] = "Mars";

console.log(rocketToPluto);

var bobby = /* record */[
  /* name */"bobby",
  /* age */3,
  /* cool */true
];

exports.bobby = bobby;
exports.karol = karol;
exports.pysia = pysia;
exports.rocketToPluto = rocketToPluto;
/*  Not a pure module */
