// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function toTeam(param) {
  return /* record */[
          /* name */param[0],
          /* titles */param[1],
          /* awsome */param[2]
        ];
}

toTeam(/* tuple */[
      "legia",
      -2063654984,
      true
    ]);

function getFirstName(mamal) {
  return mamal[/* firstName */0];
}

var legia = /* record */[
  /* name */"legia warszawa",
  /* titles */34242342,
  /* awsome */true
];

exports.legia = legia;
exports.toTeam = toTeam;
exports.getFirstName = getFirstName;
/*  Not a pure module */
