// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var eagleX = /* record */[
  /* rocketType */"EagleX 32323",
  /* currentDestination */"moon",
  /* fuel */"power xxx",
  /* luckyNum */21
];

eagleX[/* currentDestination */1] = "after the moon";

var marsDestination = /* record */[
  /* destinationName */"On to Mars",
  /* constellation */"Who knows",
  /* coordinates : tuple */[
    3232,
    342342
  ]
];

exports.eagleX = eagleX;
exports.marsDestination = marsDestination;
/*  Not a pure module */
