// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var fruitAndAnimal = /* tuple */[
  "Apple",
  4,
  "Doggie",
  2
];

console.log(fruitAndAnimal);

var numsAndFloats = /* tuple */[
  5,
  33.5,
  32.7,
  3
];

var moreNumsWithThePrevious = /* tuple */[
  1,
  2,
  2.2,
  12.2,
  numsAndFloats
];

var johnSnow = /* tuple */[
  "John",
  "snow",
  "Soldier"
];

console.log(johnSnow);

var nameAndBool = /* tuple */[
  "Tim",
  false
];

exports.fruitAndAnimal = fruitAndAnimal;
exports.numsAndFloats = numsAndFloats;
exports.moreNumsWithThePrevious = moreNumsWithThePrevious;
exports.nameAndBool = nameAndBool;
exports.johnSnow = johnSnow;
/*  Not a pure module */
