// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var karol = /* Boy */0;

var nextTurn = /* Circle */1;

exports.karol = karol;
exports.nextTurn = nextTurn;
/* No side effect */
