// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function isLarger(animal1, animal2) {
  switch (animal1) {
    case 0 : 
        return animal2 === 1;
    case 1 : 
        return false;
    case 2 : 
        return true;
    
  }
}

exports.isLarger = isLarger;
/* No side effect */
