// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function toString(field) {
  if (field) {
    if (field[0]) {
      return "O";
    } else {
      return "X";
    }
  } else {
    return "";
  }
}

var randomField = /* Marked */[/* Circle */1];

toString(randomField);

exports.toString = toString;
exports.randomField = randomField;
/*  Not a pure module */
