// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

const React = require('react');
const ReactDOMRe = require('reason-react/lib/js/src/ReactDOMRe.js');
const Timer$ReactHooksTemplate = require('./Timer.bs.js');

ReactDOMRe.renderToElementWithId(
  React.createElement(Timer$ReactHooksTemplate.make, {}),
  'root'
);

/*  Not a pure module */
